name: weather_app
description: A new Flutter project.

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Local Database 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12
  #
  flutter_bloc: ^8.1.2
  connectivity_plus: ^2.2.0
  built_value: ^8.1.2
  provider: ^6.0.1
  dartz: ^0.10.0
  chopper: ^4.0.1
  #

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  adaptive_theme: ^3.1.1
  easy_localization: ^3.0.1
  connectivity: ^3.0.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3 
  flutter_svg: ^1.1.6
  dropdown_textfield: ^1.0.8
  timezone: ^0.9.1
  bloc: ^8.1.1
  dio: ^4.0.6
  get_it: ^7.2.0
  flutter_easyloading: ^3.0.0
  freezed: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  chopper_generator: ^4.0.2
  flutter_bloc_generator: ^1.0.0
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.4
  built_value_generator: ^8.1.2


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/pictures/
    - assets/svg/
    - assets/png/

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  